#!/usr/bin/env bash

while true; do
  : ${mode:=RUBY}
  : ${git_pull:=true}

  cd "$(dirname "$0")"

  if [[ ${git_pull} = true ]]; then
    git pull
  fi

  if [[ $mode = "BASH" ]]; then
    ./meds.sh
  elif [[ $mode = "RUBY" ]]; then
    bundler install
    ./meds_runner.rb
  fi

  sleep 5
done
