#!/usr/bin/env bash

while true; do
  : ${mode:=RUBY}

  cd "$(dirname "$0")"

  git pull

  if [[ $mode = "BASH" ]]; then
    ./meds.sh
  elif [[ $mode = "RUBY" ]]; then
    ./meds_runner.rb
  fi

  sleep 5
done
